react refresh:37 Download the React DevTools for a better development experience: https://react.dev/link/react-devtools
api.js:5 🌐 API Base URL: http://localhost:5000/api
index.js:12 Root element: div#root
AuthContext.js:24 🔍 Initializing auth from localStorage...
AuthContext.js:25 Token exists: true
AuthContext.js:26 User data exists: true
AuthContext.js:37 ✓ Auth initialized with user: teacherqwe1@outlook.com
AuthContext.js:24 🔍 Initializing auth from localStorage...
AuthContext.js:25 Token exists: true
AuthContext.js:26 User data exists: true
AuthContext.js:37 ✓ Auth initialized with user: teacherqwe1@outlook.com
AuthContext.js:24 🔍 Initializing auth from localStorage...
AuthContext.js:25 Token exists: true
AuthContext.js:26 User data exists: true
AuthContext.js:37 ✓ Auth initialized with user: teacherqwe1@outlook.com
AuthContext.js:24 🔍 Initializing auth from localStorage...
AuthContext.js:25 Token exists: true
AuthContext.js:26 User data exists: true
AuthContext.js:37 ✓ Auth initialized with user: teacherqwe1@outlook.com
Header.jsx:71  Warning: [antd: Menu] `children` is deprecated. Please use `items` instead.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
typeWarning @ warning.js:46
typeWarning.deprecated @ warning.js:51
(anonymous) @ menu.js:69
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooks @ react-dom-client.development.js:7662
updateForwardRef @ react-dom-client.development.js:9724
beginWork @ react-dom-client.development.js:12117
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<ForwardRef>
exports.createElement @ react.development.js:1048
Menu @ index.js:21
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateForwardRef @ react-dom-client.development.js:9724
beginWork @ react-dom-client.development.js:12117
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Menu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:71
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
NotificationBell.jsx:245  Warning: [antd: Dropdown] `visible` is deprecated. Please use `open` instead.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
typeWarning @ warning.js:46
typeWarning.deprecated @ warning.js:51
(anonymous) @ dropdown.js:72
Dropdown @ dropdown.js:71
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooks @ react-dom-client.development.js:7662
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Dropdown>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
NotificationBell @ NotificationBell.jsx:245
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<NotificationBell>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:184
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
NotificationBell.jsx:245  Warning: [antd: Dropdown] `onVisibleChange` is deprecated. Please use `onOpenChange` instead.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
typeWarning @ warning.js:46
typeWarning.deprecated @ warning.js:51
(anonymous) @ dropdown.js:72
Dropdown @ dropdown.js:71
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooks @ react-dom-client.development.js:7662
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Dropdown>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
NotificationBell @ NotificationBell.jsx:245
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<NotificationBell>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:184
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
NotificationBell.jsx:245  Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
typeWarning @ warning.js:46
typeWarning.deprecated @ warning.js:51
(anonymous) @ dropdown.js:72
Dropdown @ dropdown.js:71
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooks @ react-dom-client.development.js:7662
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Dropdown>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
NotificationBell @ NotificationBell.jsx:245
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<NotificationBell>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:184
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
Header.jsx:200  Warning: [antd: Drawer] `bodyStyle` is deprecated. Please use `styles.body` instead.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
typeWarning @ warning.js:46
typeWarning.deprecated @ warning.js:51
(anonymous) @ index.js:78
Drawer @ index.js:77
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooks @ react-dom-client.development.js:7662
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Drawer>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:200
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
[Deprecation] -ms-high-contrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
api.js:30 [API Request] GET /notifications ✓ Token attached
api.js:30 [API Request] GET /teachers/profile ✓ Token attached
api.js:30 [API Request] GET /notifications/unread-count ✓ Token attached
api.js:30 [API Request] GET /notifications ✓ Token attached
api.js:30 [API Request] GET /teachers/profile ✓ Token attached
api.js:30 [API Request] GET /notifications/unread-count ✓ Token attached
api.js:49 [API Response] 200 /notifications ✓ Success
api.js:49 [API Response] 200 /notifications/unread-count ✓ Success
api.js:49 [API Response] 200 /notifications ✓ Success
api.js:49 [API Response] 200 /notifications/unread-count ✓ Success
api.js:134   GET http://localhost:5000/api/teachers/profile 404 (Not Found)
dispatchXhrRequest @ xhr.js:198
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
Axios.<computed> @ Axios.js:211
wrap @ bind.js:5
get @ api.js:134
fetchProfileData @ UserAccountMenu.jsx:49
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
commitPassiveMountOnFiber @ react-dom-client.development.js:15647
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15633
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15519
flushPassiveEffects @ react-dom-client.development.js:18432
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
api.js:86  [API Response Error] 404 /teachers/profile Request failed with status code 404
(anonymous) @ api.js:86
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
Axios.<computed> @ Axios.js:211
wrap @ bind.js:5
get @ api.js:134
fetchProfileData @ UserAccountMenu.jsx:49
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
commitPassiveMountOnFiber @ react-dom-client.development.js:15647
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15633
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15519
flushPassiveEffects @ react-dom-client.development.js:18432
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
UserAccountMenu.jsx:58  Failed to fetch profile data: AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
fetchProfileData @ UserAccountMenu.jsx:58
await in fetchProfileData
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
commitPassiveMountOnFiber @ react-dom-client.development.js:15647
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15633
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15476
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15718
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:15439
commitPassiveMountOnFiber @ react-dom-client.development.js:15519
flushPassiveEffects @ react-dom-client.development.js:18432
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
api.js:134   GET http://localhost:5000/api/teachers/profile 404 (Not Found)
dispatchXhrRequest @ xhr.js:198
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
Axios.<computed> @ Axios.js:211
wrap @ bind.js:5
get @ api.js:134
fetchProfileData @ UserAccountMenu.jsx:49
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15838
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
doubleInvokeEffectsOnFiber @ react-dom-client.development.js:18700
runWithFiberInDEV @ react-dom-client.development.js:870
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
commitDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18712
flushPassiveEffects @ react-dom-client.development.js:18439
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
api.js:86  [API Response Error] 404 /teachers/profile Request failed with status code 404
(anonymous) @ api.js:86
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
Axios.<computed> @ Axios.js:211
wrap @ bind.js:5
get @ api.js:134
fetchProfileData @ UserAccountMenu.jsx:49
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15838
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
doubleInvokeEffectsOnFiber @ react-dom-client.development.js:18700
runWithFiberInDEV @ react-dom-client.development.js:870
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
commitDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18712
flushPassiveEffects @ react-dom-client.development.js:18439
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
UserAccountMenu.jsx:58  Failed to fetch profile data: AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
fetchProfileData @ UserAccountMenu.jsx:58
await in fetchProfileData
(anonymous) @ UserAccountMenu.jsx:38
react_stack_bottom_frame @ react-dom-client.development.js:25989
runWithFiberInDEV @ react-dom-client.development.js:870
commitHookEffectListMount @ react-dom-client.development.js:13244
commitHookPassiveMountEffects @ react-dom-client.development.js:13334
reconnectPassiveEffects @ react-dom-client.development.js:15832
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15824
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15838
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
recursivelyTraverseReconnectPassiveEffects @ react-dom-client.development.js:15784
reconnectPassiveEffects @ react-dom-client.development.js:15885
doubleInvokeEffectsOnFiber @ react-dom-client.development.js:18700
runWithFiberInDEV @ react-dom-client.development.js:870
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
recursivelyTraverseAndDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18664
commitDoubleInvokeEffectsInDEV @ react-dom-client.development.js:18712
flushPassiveEffects @ react-dom-client.development.js:18439
flushPendingEffects @ react-dom-client.development.js:18358
performSyncWorkOnRoot @ react-dom-client.development.js:18969
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
flushSpawnedWork @ react-dom-client.development.js:18334
commitRoot @ react-dom-client.development.js:17955
commitRootWhenReady @ react-dom-client.development.js:16824
performWorkOnRoot @ react-dom-client.development.js:16722
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<UserAccountMenu>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
Header @ Header.jsx:186
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<Header>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
MainLayout @ MainLayout.jsx:11
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<MainLayout>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
App @ App.js:109
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:18957
performWorkUntilDeadline @ scheduler.development.js:45
<App>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
./src/index.js @ index.js:25
options.factory @ react refresh:37
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:7
(anonymous) @ startup:7
warning.js:30  Warning: [antd: compatible] antd v5 support React is 16 ~ 18. see https://u.ant.design/v5-for-19 for compatible.
warning @ warning.js:30
call @ warning.js:51
warningOnce @ warning.js:58
_warning @ warning.js:12
defaultReactRender @ UnstableContext.js:13
showWaveEffect @ WaveEffect.js:137
(anonymous) @ useWave.js:23
(anonymous) @ useEvent.js:10
(anonymous) @ useWave.js:36
callRef @ raf.js:30
(anonymous) @ raf.js:34
requestAnimationFrame
raf @ raf.js:9
callRef @ raf.js:33
wrapperRaf @ raf.js:41
showDebounceWave @ useWave.js:35
onClick @ index.js:38
api.js:30 [API Request] GET /notifications ✓ Token attached
api.js:49 [API Response] 200 /notifications ✓ Success
api.js:30 [API Request] POST /teachers/profile ✓ Token attached
api.js:130   POST http://localhost:5000/api/teachers/profile 400 (Bad Request)
dispatchXhrRequest @ xhr.js:198
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
httpMethod @ Axios.js:224
wrap @ bind.js:5
create @ api.js:130
handleSubmit @ TeacherProfileForm.jsx:379
(anonymous) @ button.js:188
executeDispatch @ react-dom-client.development.js:19116
runWithFiberInDEV @ react-dom-client.development.js:870
processDispatchQueue @ react-dom-client.development.js:19165
(anonymous) @ react-dom-client.development.js:19767
batchedUpdates$1 @ react-dom-client.development.js:3255
dispatchEventForPluginEventSystem @ react-dom-client.development.js:19320
dispatchEvent @ react-dom-client.development.js:23584
dispatchDiscreteEvent @ react-dom-client.development.js:23552
<button>
exports.createElement @ react.development.js:1048
Button @ button.js:261
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateForwardRef @ react-dom-client.development.js:9724
beginWork @ react-dom-client.development.js:12117
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
<Button>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
TeacherProfileForm @ TeacherProfileForm.jsx:466
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
api.js:86  [API Response Error] 400 /teachers/profile Request failed with status code 400
(anonymous) @ api.js:86
Promise.then
_request @ Axios.js:163
request @ Axios.js:40
httpMethod @ Axios.js:224
wrap @ bind.js:5
create @ api.js:130
handleSubmit @ TeacherProfileForm.jsx:379
(anonymous) @ button.js:188
executeDispatch @ react-dom-client.development.js:19116
runWithFiberInDEV @ react-dom-client.development.js:870
processDispatchQueue @ react-dom-client.development.js:19165
(anonymous) @ react-dom-client.development.js:19767
batchedUpdates$1 @ react-dom-client.development.js:3255
dispatchEventForPluginEventSystem @ react-dom-client.development.js:19320
dispatchEvent @ react-dom-client.development.js:23584
dispatchDiscreteEvent @ react-dom-client.development.js:23552
<button>
exports.createElement @ react.development.js:1048
Button @ button.js:261
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateForwardRef @ react-dom-client.development.js:9724
beginWork @ react-dom-client.development.js:12117
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
<Button>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
TeacherProfileForm @ TeacherProfileForm.jsx:466
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
TeacherProfileForm.jsx:406  Submission error: AxiosError {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
handleSubmit @ TeacherProfileForm.jsx:406
await in handleSubmit
(anonymous) @ button.js:188
executeDispatch @ react-dom-client.development.js:19116
runWithFiberInDEV @ react-dom-client.development.js:870
processDispatchQueue @ react-dom-client.development.js:19165
(anonymous) @ react-dom-client.development.js:19767
batchedUpdates$1 @ react-dom-client.development.js:3255
dispatchEventForPluginEventSystem @ react-dom-client.development.js:19320
dispatchEvent @ react-dom-client.development.js:23584
dispatchDiscreteEvent @ react-dom-client.development.js:23552
<button>
exports.createElement @ react.development.js:1048
Button @ button.js:261
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateForwardRef @ react-dom-client.development.js:9724
beginWork @ react-dom-client.development.js:12117
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
<Button>
exports.jsxDEV @ react-jsx-dev-runtime.development.js:327
TeacherProfileForm @ TeacherProfileForm.jsx:466
react_stack_bottom_frame @ react-dom-client.development.js:25904
renderWithHooksAgain @ react-dom-client.development.js:7762
renderWithHooks @ react-dom-client.development.js:7674
updateFunctionComponent @ react-dom-client.development.js:10166
beginWork @ react-dom-client.development.js:11778
runWithFiberInDEV @ react-dom-client.development.js:870
performUnitOfWork @ react-dom-client.development.js:17639
workLoopSync @ react-dom-client.development.js:17469
renderRootSync @ react-dom-client.development.js:17450
performWorkOnRoot @ react-dom-client.development.js:16498
performSyncWorkOnRoot @ react-dom-client.development.js:18972
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:18803
processRootScheduleInMicrotask @ react-dom-client.development.js:18851
(anonymous) @ react-dom-client.development.js:18986
api.js:30 [API Request] GET /notifications ✓ Token attached
api.js:49 [API Response] 200 /notifications ✓ Success
